config/routes.rb
Rm::Engine.routes.draw do
  resources :rm_analisis_portafolio, :only => [:new, :create] do
    get "listar_titulos", on: :collection
  end
  resources :rm_antecedentes_titulos, :only => [:new, :index, :create, :destroy] do
    # Realmente el parametro id se corresponde es con codigo_titulo. No con la columna id en sí.
    get 'grafica_comportamiento_historico', :on => :member, :constraints => { :id => /.+/ }
  end
  resources :rm_simulacion_montecarlo, :only => [:new, :index, :create] do
    get "listar_titulos", on: :collection
    get "descargar_valores_aleatorios", on: :collection
  end
  
  resources :rm_parametros_duration  do
    get 'editar', :on => :collection
    post 'actualizar', :on => :collection 
    get 'lista', :on => :collection   
  end
  resources :rm_duration, :only => [:new, :create]

  resources :rm_cvar, :only => [:new, :create] do
    get "listar_titulos", on: :collection
  end
  
  namespace :gestion_precios_mercado do
    resources :consulta_precios, only: [:new, :create] do
      delete 'eliminar_titulos_consultados', on: :collection
    end
    resources :rm_precios_mercado, except: [:index]
    resources :carga_masiva, only: [:new, :create]
    resources :borrado_masivo_fecha, only: [:new, :create]
    resources :borrado_masivo_titulo, only: [:new, :create]
  end
  

end

app/models/rm/gestion_precios_mercado/carga_masiva.rb
module Rm
  module GestionPreciosMercado
    class CargaMasiva
      # ---------------------------------------      
      include ActiveModel::Model
      attr_reader :archivo, :ruta_archivo_precios_mercado_subido, :error_de_carga,:ruta_archivo, :separador
      validate :debe_seleccionar_un_archivo
  		# ---------------------------------------            
  
      def initialize(parametros = {})
        if parametros.blank?        
          @separador = ArchivoPreciosMercado::SEPARADORES.first
        else
          @archivo = parametros[:archivo]
          @separador = parametros[:separador]        
        end
      end
      
      def cargar_archivo
        CargaMasiva::ArchivoPreciosMercado.new(ruta_archivo, @separador).cargar
        true
      rescue => e
        @error_de_carga = e
        # Para efectos de formulario
        errors.add(:archivo,"El archivo #{@ruta_archivo} no pudo ser cargado" )
        false
      end
       
       def ruta_archivo
         @ruta_archivo ||= preparar_archivo_subido(@archivo)
       end
                   
      private
      
      def debe_seleccionar_un_archivo
        unless @archivo
          errors.add(:archivo, 'Debe seleccionar un archivo')        
        end
      end
            
      def preparar_archivo_subido(obj_http_uploaded_file)
        raise "Para el archivo plano de precios mercado subido, se espera un objeto de tipo ActionDispatch::Http::UploadedFile" unless obj_http_uploaded_file.is_a?(ActionDispatch::Http::UploadedFile)
        tmp = obj_http_uploaded_file.tempfile
        @ruta_archivo_precios_mercado_subido = File.join('/tmp', obj_http_uploaded_file.original_filename)
        FileUtils.cp tmp.path, @ruta_archivo_precios_mercado_subido
        File.chmod(0664, @ruta_archivo_precios_mercado_subido)
        return @ruta_archivo_precios_mercado_subido
      end
  
    end
  end
end

app/models/rm/gestion_precios_mercado/carga_masiva/archivo_precios_mercado.rb
module Rm
  module GestionPreciosMercado
    class CargaMasiva::ArchivoPreciosMercado
      
      SEPARADORES = ['|',';',',']      
      attr_reader :ruta_archivo
      
      def initialize(ruta_archivo, separador = SEPARADORES.first)
        @ruta_archivo = ruta_archivo  
        @separador = SEPARADORES.include?(separador) ? separador : SEPARADORES.first              
      end
  
      def cargar
        sql =<<-QUERY
          SELECT cargar_archivo_precios_mercado('#{archivo_precios_mercado}','#{@separador}');
        QUERY
        ActiveRecord::Base.connection.execute(sql)
      ensure
        File.delete(@ruta_archivo) if File.exist?(archivo_precios_mercado)  
      end
      
      private      
      def archivo_precios_mercado
        extension = File.extname(@ruta_archivo).downcase
        case extension
        when '.csv'
          @ruta_archivo
        when '.xls','.xlsx'  
          convertir_excel_a_csv
          ruta_archivo_csv_tmp
        else
          raise "Debe subir un archivo Excel (XLSX) o CSV"
        end
      end     
      
      def convertir_excel_a_csv
        worksheet = RubyXL::Parser.parse(@ruta_archivo).first
        cantidad_columnas = worksheet.sheet_data[0].cells.size
        raise "Cantidad de columnas incorrectas en el archivo. Deben ser 8 columnas - Hay #{cantidad_columnas}" if cantidad_columnas != 8
        indice_ultima_fila = worksheet.sheet_data.size - 1
        csv = CSV.open(ruta_archivo_csv_tmp, "w",col_sep: @separador, quote_char: "\x00")
        csv << worksheet.sheet_data[0].cells.map{|c| c.value.strip }
        1.upto(indice_ultima_fila) do |i|
          @i = i + 1 # Para captura el número de línea en que posiblemente ocurrió el error.
        	celdas = worksheet.sheet_data[i].cells
        	#       FECHA_SNAPSHOT												CODIGO_TITULO	         NOMBRE	                MONTO	                PRECIO_COMPRA 	       PRECIO_MERCADO 	     FECHA_VENCIMIENTO	                   TASA_CUPON 
        	csv << [celdas[0].value.strftime("%d/%m/%Y"), celdas[1].value.strip, celdas[2].value.strip, celdas[3].value.to_f, celdas[4].value.to_f,  celdas[5].value.to_f, celdas[6].value.strftime("%d/%m/%Y"), celdas[7].value.to_f ]
        end
        csv.close        
      rescue => e 
        raise "Formato inválido en alguna columna de la línea #{@i} -> #{e.message}"
      end
      
      def ruta_archivo_csv_tmp
        "/tmp/rmpm.csv"
      end          
           
    end
  end
end

app/models/rm/gestion_precios_mercado/consulta_precios.rb
module Rm
  module GestionPreciosMercado
    class ConsultaPrecios
      # ---------------------------------------      
      include ActiveModel::Model
      validate :validar_fecha_especifica
      validate :validar_rangos_de_fechas
  		# ---------------------------------------      

      # Este hash es canónico
      TIPO_CONSULTA_PRECIOS_MERCADO = {
        consulta_fecha_especifica: 'Precios mercado de todos los títulos a la fecha indicada',
        consulta_rango_de_fechas: 'Histórico de precios para un título indicado'
      }

      # Para ser mostrados en el formulario
      attr_reader :fecha_hasta, :fecha_desde, :fecha_snapshot, :codigo_titulo, :tipo_consulta_precios, :rm_precios_mercado_ids
      
      def initialize(parametros = {})
        if parametros.blank?
          @tipo_consulta_precios = :consulta_fecha_especifica
          @fecha_snapshot = RmPrecioMercado.maximum(:fecha_snapshot)
          @fecha_desde = @fecha_snapshot - 2.years 
          @fecha_hasta = @fecha_snapshot
        else 
          @tipo_consulta_precios = parametros[:tipo_consulta_precios].to_sym 
          @fecha_snapshot = Util::Fecha.objeto_fecha(parametros[:fecha_snapshot]) 
          @fecha_desde = Util::Fecha.objeto_fecha(parametros[:fecha_desde])
          @fecha_hasta = Util::Fecha.objeto_fecha(parametros[:fecha_hasta])
          @codigo_titulo = parametros[:codigo_titulo] 
        end
      end
      
      def titulos_consultados
        @titulos_consultados ||= if valid?
                                   case @tipo_consulta_precios
                                     when :consulta_fecha_especifica
                                       ConsultaPrecios::PreciosEnUnDia.new({fecha_snapshot: @fecha_snapshot}).buscar
                                     when :consulta_rango_de_fechas
                                       ConsultaPrecios::HistoricoPreciosPorTitulo.new({fecha_desde: @fecha_desde, fecha_hasta: @fecha_hasta, codigo_titulo: @codigo_titulo}).buscar
                                   end
                                 else
                                   []
                                 end          
      end
      
      def self.codigos_titulos
        RmPrecioMercado.select(:codigo_titulo).distinct.order(:codigo_titulo).pluck(:codigo_titulo)
      end
      
      
      def consulta_fecha_especifica?
			    @tipo_consulta_precios == :consulta_fecha_especifica
		  end
		
  		def consulta_rango_de_fechas?
  			@tipo_consulta_precios == :consulta_rango_de_fechas
  		end
      
      private			
      # Validadores --------------------------------------------------------------------------------
      def validar_rangos_de_fechas
        if consulta_rango_de_fechas?  
          if @codigo_titulo.blank?
            errors.add(:codigo_titulo, 'Debe seleccionar un título')
          end
          if @fecha_desde.present? and @fecha_hasta.present?           
            if @fecha_desde >= @fecha_hasta
              errors.add(:fecha_desde, 'Las fechas de consulta están solapadas')
            end
          else
            if @fecha_desde.blank?
              errors.add(:fecha_desde, 'Debe seleccionar una fecha inicial de consulta')
            end
            if @fecha_hasta.blank?
              errors.add(:fecha_hasta, 'Debe selecionar una fecha final de consulta')
            end						
          end				
        end
      end
      
      def validar_fecha_especifica
        if consulta_fecha_especifica?
          if @fecha_snapshot.blank?
            errors.add(:fecha_snapshot, 'Debe seleccionar la fecha de consulta')					
          elsif @fecha_snapshot > RmPrecioMercado.maximum(:fecha_snapshot)
            errors.add(:fecha_snapshot, "No hay precios mercado con fecha superior a: #{ RmPrecioMercado.maximum(:fecha_snapshot).try(:strftime,"%d/%m/%Y")}")
          end			
        end
      end      
      
      

    end
  end
end

app/models/rm/gestion_precios_mercado/consulta_precios/historico_precios_por_titulo.rb
module Rm
  module GestionPreciosMercado
    class ConsultaPrecios::HistoricoPreciosPorTitulo
      def initialize(parametros = {})
        @fecha_desde = parametros.fetch(:fecha_desde)
        @fecha_hasta = parametros.fetch(:fecha_hasta)
        @codigo_titulo = parametros.fetch(:codigo_titulo)
      end
      
      def buscar
        sql = <<-SQL 
          select id, fecha_snapshot, codigo_titulo, nombre, monto, precio_compra, precio_mercado, fecha_vencimiento, tasa_cupon
            from rm_precios_mercado
           where fecha_snapshot between '#{@fecha_desde.to_s}' and '#{@fecha_hasta.to_s}'
             and codigo_titulo = '#{@codigo_titulo}'
        SQL
        @buscar ||= ActiveRecord::Base.connection.select_all(sql).to_a
      rescue
        []        
      end
      
    end
  end
end

app/models/rm/gestion_precios_mercado/consulta_precios/precios_en_un_dia.rb
module Rm
  module GestionPreciosMercado
    class ConsultaPrecios::PreciosEnUnDia
      def initialize(parametros)
        @fecha_snapshot = parametros.fetch(:fecha_snapshot)
      end
      
      def buscar
        sql = <<-SQL 
          select id, fecha_snapshot, codigo_titulo, nombre, monto, precio_compra, precio_mercado, fecha_vencimiento, tasa_cupon
            from rm_precios_mercado
           where fecha_snapshot = '#{@fecha_snapshot.to_s}'
           order by codigo_titulo
        SQL
        @buscar ||= ActiveRecord::Base.connection.select_all(sql).to_a        
      end
      
    end
  end
end

app/controllers/rm/gestion_precios_mercado/carga_masiva_controller.rb
module Rm
  module GestionPreciosMercado
    class CargaMasivaController < ApplicationController
      authorize_resource
      def new
        @carga_masiva = CargaMasiva.new
      end

      def create
        @carga_masiva  = CargaMasiva.new(params[:gestion_precios_mercado_carga_masiva])
        unless @carga_masiva.cargar_archivo
          render 'new'
        end  
      end
      
    end
  end
end

app/controllers/rm/gestion_precios_mercado/consulta_precios_controller.rb
module Rm
  module GestionPreciosMercado
    class ConsultaPreciosController < ApplicationController
      authorize_resource class: ConsultaPrecios
      def new
        @consulta_precios = ConsultaPrecios.new
        unless RmPrecioMercado.any?
          redirect_to baseweb.root_path, notice: "Debe cargar un histórico de precios mercado para gestionar los precios"
        end 
      end

      def create
        #render plain: params.inspect
        @consulta_precios = ConsultaPrecios.new(params[:gestion_precios_mercado_consulta_precios])
        unless @consulta_precios.valid?        
          render 'new'
        end         
      end
      
      def eliminar_titulos_consultados
        RmPrecioMercado.delete(params[:rm_precios_mercado_ids])
      end
      
    end
  end
end

app/controllers/rm/gestion_precios_mercado/rm_precios_mercado_controller.rb
module Rm
  module GestionPreciosMercado
    class RmPreciosMercadoController < ApplicationController
      load_and_authorize_resource
      before_action :set_rm_precio_mercado, only: [:show, :edit, :update, :destroy]
      def new
        @rm_precio_mercado = RmPrecioMercado.new
      end
      
      def create
        @rm_precio_mercado = RmPrecioMercado.new(rm_precio_mercado_params)
        if @rm_precio_mercado.save
          redirect_to gestion_precios_mercado_rm_precio_mercado_path(@rm_precio_mercado), notice: "Transacción de título #{@rm_precio_mercado.codigo_titulo} insertada"
        else 
          render 'new'
        end
      end
      
      def edit
      end
      
      def show
      end

      def update
        if @rm_precio_mercado.update(rm_precio_mercado_params)
          redirect_to gestion_precios_mercado_rm_precio_mercado_path(@rm_precio_mercado), notice: "Transacción de título #{@rm_precio_mercado.codigo_titulo} actualizada"
        else
          render :edit
        end
      end

      def destroy
        codigo_titulo = @rm_precio_mercado.codigo_titulo
        @rm_precio_mercado.destroy
        redirect_to new_gestion_precios_mercado_consulta_precios_url, notice: "Transacción de título #{codigo_titulo} actualizada"
      end

      
      private
      # Use callbacks to share common setup or constraints between actions.
      def set_rm_precio_mercado
        @rm_precio_mercado = RmPrecioMercado.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def rm_precio_mercado_params
        params.require(:rm_precio_mercado).permit(:fecha_snapshot, :codigo_titulo, :nombre, :monto, :precio_compra, :precio_mercado, :fecha_vencimiento, :tasa_cupon)
      end      
      
    end
  end
end

app/views/rm/gestion_precios_mercado/consulta_precios/_eliminar_titulos_consultados.html.erb
<% if can? :eliminar_titulos_consultados,  Rm::GestionPreciosMercado::ConsultaPrecios %>
  <%= callout("Eliminación en PRECIOS MERCADO", :danger) %>
  <%= form_for(@consulta_precios, url: eliminar_titulos_consultados_gestion_precios_mercado_consulta_precios_index_path, method: :delete) do |f| %>
    <% @consulta_precios.titulos_consultados.each do |titulo| %>
      <%= hidden_field_tag 'rm_precios_mercado_ids[]',  titulo.id %>
    <% end %>  
    <div class="row">
      <div class="col-md-6">
        <div class="alert alert-danger text-center">
            Los resultados generados de la consuluta efectuada pueden ser eliminados: &nbsp;&nbsp;
            <%= button_tag(type: 'submit', class: "btn btn-danger", data: { confirm: "¿Está seguro que desea eliminar los precios consultados?" }) do %>
              <i class="fa fa-trash"></i> Eliminar
            <% end %>
        </div>
      </div>  
    </div>
  <% end %>
<% end %>

app/views/rm/gestion_precios_mercado/consulta_precios/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <div class="panel panel-primary">
      <div class="panel-heading"><strong>Parámetros de la consulta</strong></div>
      <div class="panel-body">
        <%= simple_form_for(@consulta_precios) do |f| %>
          <div class="row">
            <div class="col-md-10">
              <%= f.input :tipo_consulta_precios,  label: 'Tipo de consulta:', collection: Rm::GestionPreciosMercado::ConsultaPrecios::TIPO_CONSULTA_PRECIOS_MERCADO.map {|k,v| [v,k]}, as: :radio_buttons %>
            </div>
          </div>
          <div id="consulta_titulo_precios_mercado_fecha_especifica">            
            <p class="alert alert-info">
              Se consultará los precios de todos los títulos a la fecha especificada
            </p>
            <div class="row"  >
              <div class="col-md-5">
                <%= campo_fecha(f, :fecha_snapshot, 'Fecha especifica:', 'Fecha específica de consulta de títulos') %>
              </div>
            </div> 
          </div>                             
          <div  id="consulta_titulo_precios_mercado_rango_de_fechas">
            <p class="alert alert-warning">
              Se consultará la história de un título en específico para un rango de fechas
            </p>
            <div class="row">
              <div class="col-md-6">
                <%= campo_fecha(f, :fecha_desde, 'Fecha inicial de consulta:', 'Fecha incial de la carga') %>
              </div>
              <div class="col-md-6">
                <%= campo_fecha(f, :fecha_hasta, 'Fecha final de consulta:', 'Fecha final de la carga') %>
              </div>              
            </div>    
              <div class="row">
                <div class="col-md-8">          
                  <%= f.input :codigo_titulo, label: "Código del Título en PRECIOS MERCADO", collection: Rm::GestionPreciosMercado::ConsultaPrecios.codigos_titulos, include_blank: "SELECCIONE" %>
                </div>
              </div>
          </div>  
          <div class="row">
            <div class="col-md-6">
              <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
                <i class="fa fa-search"></i> Consultar
              <% end %>              
            </div>
            <% if can? :new, RmPrecioMercado %>
              <div class="col-md-6 text-right">
                <%= link_to new_gestion_precios_mercado_rm_precio_mercado_path, class: 'btn btn-warning' do %>
                <i class="fa fa-arrow-right"></i> Nuevo precio mercado
                <% end %>               
              </div>
            <% end %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div> 

app/views/rm/gestion_precios_mercado/consulta_precios/create.html.erb
<% content_for( :titulo ){'Resultados de la consulta de precios mercado'} %>
<%= render 'form' %>
<div class="panel panel-default">
  <div class="panel-body">
      <%= callout("Títulos en PRECIOS MERCADO", :warning) %>
      <div class="table-responsive">
        <table id="resultado_consulta_precios_mercado" class="datatable-calculos">
          <thead>
            <tr>
              <th class="text-center">FECHA_SNAPSHOT</th>
              <th class="text-center">CODIGO_TITULO</th>
              <th class="text-center">NOMBRE</th>
              <th class="text-center">FECHA_VENCIMIENTO</th>
              <th class="text-right">MONTO</th>
              <th class="text-right">PRECIO_COMPRA</th>
              <th class="text-right">TASA_CUPON</th>
              <th class="text-right">PRECIO_MERCADO</th>
              <% if can? :edit, RmPrecioMercado or can? :destroy, RmPrecioMercado   %>                
                <th class="text-right">OPERACIONES</th>
              <% end %>
            </tr>
          </thead>
          <tbody class="centrado">
            <% @consulta_precios.titulos_consultados.each do |titulo| %>
            <tr>
              <td><%= Date.parse(titulo['fecha_snapshot']).strftime('%d/%m/%Y') %></td>
              <td><%= titulo['codigo_titulo'] %></td>
              <td><%= titulo['nombre'] %></td>
              <td class="text-center"><%= Date.parse(titulo['fecha_vencimiento']).strftime('%d/%m/%Y') %></td>
              <td class="text-right"><%= titulo['monto'] %></td>
              <td class="text-right"><%= titulo['precio_compra'] %></td>
              <td class="text-right"><%= titulo['tasa_cupon'] %></td>
              <td class="text-right precio_mercado"><%= titulo['precio_mercado'] %></td>
              <% if can? :edit, RmPrecioMercado or can? :destroy, RmPrecioMercado  %>
                <td class="text-center">
                  <% if can? :edit, RmPrecioMercado %>
                    <%= link_to edit_gestion_precios_mercado_rm_precio_mercado_path(titulo['id']) do %>
                    <i class="fa fa-edit" title="Editar datos"></i>
                    <% end %>
                  <% end %>
                  <% if can? :destroy, RmPrecioMercado %>
                    <%= link_to gestion_precios_mercado_rm_precio_mercado_path(titulo['id']), method: :delete, data: { confirm: 'Are you sure?' }, style: 'color: red' do %>
                    <i class="fa fa-trash" title="Borrar precio"></i>
                    <% end %>
                  <% end %>
                </td>
              <% end %>
            </tr>
            <% end %>            
          </tbody>
        </table>
      </div>
      <br>
      <%= render 'eliminar_titulos_consultados' if  @consulta_precios.titulos_consultados.any? %>
      
  </div>
</div>

app/views/rm/gestion_precios_mercado/consulta_precios/eliminar_titulos_consultados.html.erb
<% content_for( :titulo ){'Carga masiva de precio mercado'} %>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading"><strong>Resultados de la eliminación</strong></div>
      <div class="panel-body">
        <br>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div class="alert alert-info text-center">
              <p style="font-size: 1.2em"><i class="fa fa-trash"></i> - La eliminación se efectuó satisfactoriamente de la tabla de PRECIOS MERCADO</p>
            </div>            
          </div>
        </div>
        <div class="text-center">
          <%= link_to new_gestion_precios_mercado_consulta_precios_path, class: 'btn btn-warning' do %>
          <i class="fa fa-search"></i> Consultar precios mercado
          <% end %>  
        </div>        
      </div>
    </div>
  </div>
</div> 

app/views/rm/gestion_precios_mercado/consulta_precios/new.html.erb
<% content_for( :titulo ){'Consulta de precios mercado'} %>
<%= render 'form' %>