config/routes.rb
Rm::Engine.routes.draw do
  resources :rm_analisis_portafolio, :only => [:new, :create] do
    get "listar_titulos", on: :collection
  end
  resources :rm_antecedentes_titulos, :only => [:new, :index, :create, :destroy] do
    # Realmente el parametro id se corresponde es con codigo_titulo. No con la columna id en sí.
    get 'grafica_comportamiento_historico', :on => :member, :constraints => { :id => /.+/ }
  end
  resources :rm_simulacion_montecarlo, :only => [:new, :index, :create] do
    get "listar_titulos", on: :collection
    get "descargar_valores_aleatorios", on: :collection
  end
  
  resources :rm_parametros_duration  do
    get 'editar', :on => :collection
    post 'actualizar', :on => :collection 
    get 'lista', :on => :collection   
  end
  resources :rm_duration, :only => [:new, :create]

  resources :rm_cvar, :only => [:new, :create] do
    get "listar_titulos", on: :collection
  end
  
  namespace :gestion_precios_mercado do
    resources :consulta_precios, only: [:new, :create] do
      delete 'eliminar_titulos_consultados', on: :collection
    end
    resources :rm_precios_mercado, except: [:index]
    resources :carga_masiva, only: [:new, :create]
    resources :borrado_masivo_fecha, only: [:new, :create]
    resources :borrado_masivo_titulo, only: [:new, :create]
  end
  

end

app/models/rm/gestion_precios_mercado/carga_masiva.rb
module Rm
  module GestionPreciosMercado
    class CargaMasiva
      # ---------------------------------------      
      include ActiveModel::Model
      attr_reader :archivo, :ruta_archivo_precios_mercado_subido, :error_de_carga,:ruta_archivo, :separador
      validate :debe_seleccionar_un_archivo
  		# ---------------------------------------            
  
      def initialize(parametros = {})
        if parametros.blank?        
          @separador = ArchivoPreciosMercado::SEPARADORES.first
        else
          @archivo = parametros[:archivo]
          @separador = parametros[:separador]        
        end
      end
      
      def cargar_archivo
        CargaMasiva::ArchivoPreciosMercado.new(ruta_archivo, @separador).cargar
        true
      rescue => e
        @error_de_carga = e
        # Para efectos de formulario
        errors.add(:archivo,"El archivo #{@ruta_archivo} no pudo ser cargado" )
        false
      end
       
       def ruta_archivo
         @ruta_archivo ||= preparar_archivo_subido(@archivo)
       end
                   
      private
      
      def debe_seleccionar_un_archivo
        unless @archivo
          errors.add(:archivo, 'Debe seleccionar un archivo')        
        end
      end
            
      def preparar_archivo_subido(obj_http_uploaded_file)
        raise "Para el archivo plano de precios mercado subido, se espera un objeto de tipo ActionDispatch::Http::UploadedFile" unless obj_http_uploaded_file.is_a?(ActionDispatch::Http::UploadedFile)
        tmp = obj_http_uploaded_file.tempfile
        @ruta_archivo_precios_mercado_subido = File.join('/tmp', obj_http_uploaded_file.original_filename)
        FileUtils.cp tmp.path, @ruta_archivo_precios_mercado_subido
        File.chmod(0664, @ruta_archivo_precios_mercado_subido)
        return @ruta_archivo_precios_mercado_subido
      end
  
    end
  end
end

app/models/rm/gestion_precios_mercado/carga_masiva/archivo_precios_mercado.rb
module Rm
  module GestionPreciosMercado
    class CargaMasiva::ArchivoPreciosMercado
      
      SEPARADORES = ['|',';',',']      
      attr_reader :ruta_archivo
      
      def initialize(ruta_archivo, separador = SEPARADORES.first)
        @ruta_archivo = ruta_archivo  
        @separador = SEPARADORES.include?(separador) ? separador : SEPARADORES.first              
      end
  
      def cargar
        sql =<<-QUERY
          SELECT cargar_archivo_precios_mercado('#{archivo_precios_mercado}','#{@separador}');
        QUERY
        ActiveRecord::Base.connection.execute(sql)
      ensure
        File.delete(@ruta_archivo) if File.exist?(archivo_precios_mercado)  
      end
      
      private      
      def archivo_precios_mercado
        extension = File.extname(@ruta_archivo).downcase
        case extension
        when '.csv'
          @ruta_archivo
        when '.xls','.xlsx'  
          convertir_excel_a_csv
          ruta_archivo_csv_tmp
        else
          raise "Debe subir un archivo Excel (XLSX) o CSV"
        end
      end     
      
      def convertir_excel_a_csv
        worksheet = RubyXL::Parser.parse(@ruta_archivo).first
        cantidad_columnas = worksheet.sheet_data[0].cells.size
        raise "Cantidad de columnas incorrectas en el archivo. Deben ser 8 columnas - Hay #{cantidad_columnas}" if cantidad_columnas != 8
        indice_ultima_fila = worksheet.sheet_data.size - 1
        csv = CSV.open(ruta_archivo_csv_tmp, "w",col_sep: @separador, quote_char: "\x00")
        csv << worksheet.sheet_data[0].cells.map{|c| c.value.strip }
        1.upto(indice_ultima_fila) do |i|
          @i = i + 1 # Para captura el número de línea en que posiblemente ocurrió el error.
        	celdas = worksheet.sheet_data[i].cells
        	#       FECHA_SNAPSHOT												CODIGO_TITULO	         NOMBRE	                MONTO	                PRECIO_COMPRA 	       PRECIO_MERCADO 	     FECHA_VENCIMIENTO	                   TASA_CUPON 
        	csv << [celdas[0].value.strftime("%d/%m/%Y"), celdas[1].value.strip, celdas[2].value.strip, celdas[3].value.to_f, celdas[4].value.to_f,  celdas[5].value.to_f, celdas[6].value.strftime("%d/%m/%Y"), celdas[7].value.to_f ]
        end
        csv.close        
      rescue => e 
        raise "Formato inválido en alguna columna de la línea #{@i} -> #{e.message}"
      end
      
      def ruta_archivo_csv_tmp
        "/tmp/rmpm.csv"
      end          
           
    end
  end
end

app/models/rm/gestion_precios_mercado/consulta_precios.rb
module Rm
  module GestionPreciosMercado
    class ConsultaPrecios
      # ---------------------------------------      
      include ActiveModel::Model
      validate :validar_fecha_especifica
      validate :validar_rangos_de_fechas
  		# ---------------------------------------      

      # Este hash es canónico
      TIPO_CONSULTA_PRECIOS_MERCADO = {
        consulta_fecha_especifica: 'Precios mercado de todos los títulos a la fecha indicada',
        consulta_rango_de_fechas: 'Histórico de precios para un título indicado'
      }

      # Para ser mostrados en el formulario
      attr_reader :fecha_hasta, :fecha_desde, :fecha_snapshot, :codigo_titulo, :tipo_consulta_precios, :rm_precios_mercado_ids
      
      def initialize(parametros = {})
        if parametros.blank?
          @tipo_consulta_precios = :consulta_fecha_especifica
          @fecha_snapshot = RmPrecioMercado.maximum(:fecha_snapshot)
          @fecha_desde = @fecha_snapshot - 2.years 
          @fecha_hasta = @fecha_snapshot
        else 
          @tipo_consulta_precios = parametros[:tipo_consulta_precios].to_sym 
          @fecha_snapshot = Util::Fecha.objeto_fecha(parametros[:fecha_snapshot]) 
          @fecha_desde = Util::Fecha.objeto_fecha(parametros[:fecha_desde])
          @fecha_hasta = Util::Fecha.objeto_fecha(parametros[:fecha_hasta])
          @codigo_titulo = parametros[:codigo_titulo] 
        end
      end
      
      def titulos_consultados
        @titulos_consultados ||= if valid?
                                   case @tipo_consulta_precios
                                     when :consulta_fecha_especifica
                                       ConsultaPrecios::PreciosEnUnDia.new({fecha_snapshot: @fecha_snapshot}).buscar
                                     when :consulta_rango_de_fechas
                                       ConsultaPrecios::HistoricoPreciosPorTitulo.new({fecha_desde: @fecha_desde, fecha_hasta: @fecha_hasta, codigo_titulo: @codigo_titulo}).buscar
                                   end
                                 else
                                   []
                                 end          
      end
      
      def self.codigos_titulos
        RmPrecioMercado.select(:codigo_titulo).distinct.order(:codigo_titulo).pluck(:codigo_titulo)
      end
      
      
      def consulta_fecha_especifica?
			    @tipo_consulta_precios == :consulta_fecha_especifica
		  end
		
  		def consulta_rango_de_fechas?
  			@tipo_consulta_precios == :consulta_rango_de_fechas
  		end
      
      private			
      # Validadores --------------------------------------------------------------------------------
      def validar_rangos_de_fechas
        if consulta_rango_de_fechas?  
          if @codigo_titulo.blank?
            errors.add(:codigo_titulo, 'Debe seleccionar un título')
          end
          if @fecha_desde.present? and @fecha_hasta.present?           
            if @fecha_desde >= @fecha_hasta
              errors.add(:fecha_desde, 'Las fechas de consulta están solapadas')
            end
          else
            if @fecha_desde.blank?
              errors.add(:fecha_desde, 'Debe seleccionar una fecha inicial de consulta')
            end
            if @fecha_hasta.blank?
              errors.add(:fecha_hasta, 'Debe selecionar una fecha final de consulta')
            end						
          end				
        end
      end
      
      def validar_fecha_especifica
        if consulta_fecha_especifica?
          if @fecha_snapshot.blank?
            errors.add(:fecha_snapshot, 'Debe seleccionar la fecha de consulta')					
          elsif @fecha_snapshot > RmPrecioMercado.maximum(:fecha_snapshot)
            errors.add(:fecha_snapshot, "No hay precios mercado con fecha superior a: #{ RmPrecioMercado.maximum(:fecha_snapshot).try(:strftime,"%d/%m/%Y")}")
          end			
        end
      end      
      
      

    end
  end
end

app/models/rm/gestion_precios_mercado/consulta_precios/historico_precios_por_titulo.rb
module Rm
  module GestionPreciosMercado
    class ConsultaPrecios::HistoricoPreciosPorTitulo
      def initialize(parametros = {})
        @fecha_desde = parametros.fetch(:fecha_desde)
        @fecha_hasta = parametros.fetch(:fecha_hasta)
        @codigo_titulo = parametros.fetch(:codigo_titulo)
      end
      
      def buscar
        sql = <<-SQL 
          select id, fecha_snapshot, codigo_titulo, nombre, monto, precio_compra, precio_mercado, fecha_vencimiento, tasa_cupon
            from rm_precios_mercado
           where fecha_snapshot between '#{@fecha_desde.to_s}' and '#{@fecha_hasta.to_s}'
             and codigo_titulo = '#{@codigo_titulo}'
        SQL
        @buscar ||= ActiveRecord::Base.connection.select_all(sql).to_a
      rescue
        []        
      end
      
    end
  end
end

app/models/rm/gestion_precios_mercado/consulta_precios/precios_en_un_dia.rb
module Rm
  module GestionPreciosMercado
    class ConsultaPrecios::PreciosEnUnDia
      def initialize(parametros)
        @fecha_snapshot = parametros.fetch(:fecha_snapshot)
      end
      
      def buscar
        sql = <<-SQL 
          select id, fecha_snapshot, codigo_titulo, nombre, monto, precio_compra, precio_mercado, fecha_vencimiento, tasa_cupon
            from rm_precios_mercado
           where fecha_snapshot = '#{@fecha_snapshot.to_s}'
           order by codigo_titulo
        SQL
        @buscar ||= ActiveRecord::Base.connection.select_all(sql).to_a        
      end
      
    end
  end
end

app/models/rm/parametros/administracion.rb
module Rm
	module Parametros::Administracion
		def self.rails_admin_included_models
			[ RmParametrosVarMercado, Rm::RmBaseCalculo, Rm::RmCategoriaInstrumento,
				Rm::RmCustodio, Rm::RmEmisor, Rm::RmTipoInstrumento, Rm::RmTipoInversion,
				Rm::RmTipoOperacion, Rm::RmTipoVencimientoPasivo,
				Rm::RmSimulacionMontecarlo::RmParametrosSimulacionMontecarlo, Rm::RmParametrosVarMercado
			]
   end
	end
end

app/models/rm/permisos/definiciones_incondicionales.rb
module Rm
  module Permisos::DefinicionesIncondicionales

    def accesos_incondicionales
      cannot [:new, :destroy], RmParametrosVarMercado
    end

  end
end

app/models/rm/rm_analisis_portafolio.rb
module Rm
  class RmAnalisisPortafolio

    include ActiveModel::Model
    TIPO_DE_GESTION = [['REPORTE CONSOLIDADO',0], ['VAR TITULOS',1], ['BACKTESTING SOBRE POSICION',2], ['BACKTESTING SOBRE PRECIO',3] ]

    # Para ser mostrados en el formulario
    attr_reader :fecha_de_estudio, :tipo_cartera, :tipo_de_gestion, :intervalo_de_confianza, :rm_inversion_codigo, :numero_de_muestras_temporal, :numero_de_muestras_backtesting

    # Api de la clase para calculos
    attr_reader :calculo_var, :reporte_consolidado, :backtesting

    # Variables para la vista
    attr_reader :serie_acotada, :serie_precios_mercado_y_variaciones, :precio_mercado

    # Validaciones
    validates :intervalo_de_confianza, numericality: {greater_than: 1, less_than: 100}
    validates :numero_de_muestras_temporal, :presence => true, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => RmParametrosVarMercado.first.numero_muestras_desviacion_estandar }
    validates :numero_de_muestras_backtesting, :presence => true,:numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => RmParametrosVarMercado.first.maxima_cantidad_muestras_backtesting }
    validate :verificar_si_titulo_no_contiene_informacion_a_la_fecha_de_estudio

    def initialize(atributos = {})
      if atributos.blank?
        @fecha_de_estudio = RmAnalisisPortafolio.fecha_limite
        @intervalo_de_confianza = 95
        @numero_de_muestras_temporal = RmParametrosVarMercado.first.numero_muestras_desviacion_estandar.to_i
        @numero_de_muestras_backtesting = RmParametrosVarMercado.first.maxima_cantidad_muestras_backtesting.to_i          
        @tipo_cartera = RmAnalisisPortafolio::TipoCartera.listar_codigos.first
      else
        # Atributo propio del modelo
        @tipo_de_gestion = atributos[:tipo_de_gestion].to_i

        # Atributos de las clases colaboradoras
        @fecha_de_estudio =  Util::Fecha.objeto_fecha(atributos[:fecha_de_estudio])
        @tipo_cartera = atributos[:tipo_cartera].to_i
        @numero_de_muestras_temporal = atributos[:numero_de_muestras_temporal].to_i
        @numero_de_muestras_backtesting = atributos[:numero_de_muestras_backtesting].to_i        
        @intervalo_de_confianza = atributos[:intervalo_de_confianza]
        @rm_inversion_codigo = atributos[:rm_inversion_codigo]

        parametros = { numero_de_muestras_temporal: @numero_de_muestras_temporal,
                       numero_de_muestras_backtesting: @numero_de_muestras_backtesting,          
                       intervalo_de_confianza: @intervalo_de_confianza }

        @obj_serie =  RmAnalisisPortafolio::Serie.new(@fecha_de_estudio, @tipo_cartera, @rm_inversion_codigo)

        # Las tres instancias están disponibles
        if valid? # Si la instanciación se hace desde esta clase proxy, entonces los parámetros deben ser válidos
          @calculo_var = RmAnalisisPortafolio::CalculoVar.new(parametros.merge({pivote: @obj_serie.valor_primer_dia('posicion'), serie_variaciones: @obj_serie.serie_variaciones.take(@numero_de_muestras_temporal)}))
          @backtesting =  RmAnalisisPortafolio::CalculoBacktesting.new(parametros.merge({obj_serie: @obj_serie, columna_calculo: columna_calculo_para_backtesting}))

          parametros_reporte_consolidado = parametros.merge({
                                                              fecha_de_estudio: @fecha_de_estudio,
                                                              tipo_cartera: @tipo_cartera,
                                                              titulos_en_cartera_a_la_fecha_de_estudio: @obj_serie.titulos_en_cartera_a_la_fecha_de_estudio,
                                                            })

          @reporte_consolidado = RmAnalisisPortafolio::ReporteConsolidado.new(parametros_reporte_consolidado)

          # Para la interfaz gráfica (HTML)
          @serie_precios_mercado_y_variaciones = @obj_serie.serie_precios_mercado_y_variaciones.take(@numero_de_muestras_temporal)
          @serie_acotada = @obj_serie.serie.take(@numero_de_muestras_temporal)
          @precio_mercado = @obj_serie.valor_primer_dia('precio')
        end
      end
    end

    def titulos_en_cartera_que_no_existen_en_precios_mercado
      # Sólo se dejan los títulos de la cartera que no existen en RM_PRECIOS_MERCADO
      @obj_serie.titulos_en_cartera_que_no_existen_en_precios_mercado
    end


    def self.fecha_limite
      RmPrecioMercado.maximum(:fecha_snapshot)
    end

    private
    def columna_calculo_para_backtesting
      case @tipo_de_gestion
        when 3 then # 'BACKTESTING SOBRE PRECIO'
          'precio'
        else # 'BACKTESTING SOBRE POSICION'
          'posicion'
      end
    end

    def verificar_si_titulo_no_contiene_informacion_a_la_fecha_de_estudio
      # Esta validacion aplica sólo si seleccionó un título. Por lo tanto @instrumento es instancia de RmAnalisisPortafolio::Titulo
      if serie_no_tiene_informacion_a_la_fecha_de_estudio?
        errors.add(:fecha_de_estudio, 'El título o cartera no posee información a la fecha indicada.')
      end
    end

    # Método para verificar si se pueden hacer los cálculos
    def serie_no_tiene_informacion_a_la_fecha_de_estudio?
      # Si la primera fecha de la serie es diferente a la de la fecha de estudio
      # es por que hay registros con fechas mas antiguas o no hay registros
      @obj_serie.serie.first['fecha_snapshot'].to_s != @fecha_de_estudio.to_s
    end

  end
end

app/views/rm/rm_parametros_duration/editar.html.erb
<% content_for( :titulo ){'Parámetros para el cálculo duration'} %>
<div class="panel panel-default">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= callout("Edición de los parámetros",:danger) %>              
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="well well-sm">
            <div class="row">
              <div class="col-md-12">
                <p class="titulo_parametros_duration">Listado de la cartera de títulos de mercado (RMCI)</p>
                <span>Para efectuar los calculos de duration por cada titulo presente en la cartera de inversion se requiere definir: Valor de rescate y Frecuencia de pago</span>
              </div>            
            </div>
          </div>
        </div>
      </div>    

  	<%= simple_form_for( :rm_inversiones, :url => actualizar_rm_parametros_duration_index_path, :html => {:method => :post}) do |q|%>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="table-responsive caja_altura_fija_con_scroll">
          <table class="table table-hover table-bordered table-data-calculos">
            <thead>
              <tr>
                <th>Codigo Titulo</th>
                <th>Nombre</th>
                <th>Valor de Rescate</th>
                <th>Frecuencia de Pagos</th>
              </tr>            
            </thead>
  		      <tbody>
              <% @rm_inversiones.each do |inversion| %>
                <%= q.simple_fields_for "rm_inversiones[]", inversion do |f| %>
                <tr>
                  <td><%= inversion.codigo %></td>
                  <td><%= inversion.nombre %></td>
                  <td class="editar_parametros_duration"><%= f.input :valor_rescate, :label=> false, :input_html => {:class => 'text_field', :type=>'text', required: true}, :label_html=>{:class =>'label'} %></td>    	
                  <td class="editar_parametros_duration"><%= f.input :frecuencia_pago, collection: Rm::RmDuration::FRECUENCIAS, :label=> false, :input_html => {:class => 'text_field'}, :label_html=>{:class =>'label'} %></td>    	
                </tr>
                <% end %>
              <% end %>
  		      </tbody>
          </table>
        </div>
        <div class="text-center">
      		<%= link_to 'Cancelar', lista_rm_parametros_duration_index_path, class:'btn btn-danger'%>
      		<button class="btn btn-primary" type="submit">Actualizar</button>
      	</div>
      </div>
    </div>
  	<% end %>
  </div>
</div>

app/views/rm/rm_parametros_duration/lista.html.erb
<% content_for( :titulo ){'Parámetros para el cálculo duration'} %>
<div class="panel panel-default">
  <div class="panel-body">
    <%= callout("Parametros para el calculo de Duration",:danger) %>        
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="well well-sm">
          <div class="row">
            <div class="col-md-8">
              <p class="titulo_parametros_duration">Listado de la cartera de títulos de mercado (RMCI)</p>
              <span>Los valores para edición de los títulos son el <strong>VALOR RESCATE</strong> y <strong>FRECUENCIA DE PAGO</strong></span>
            </div>
            <% if can? :editar, :rm_parametros_duration %>
              <div class="col-md-4 text-right" style="padding-top: 5px">
                <%= link_to editar_rm_parametros_duration_index_path, class: 'btn btn-info' do %> 
                <i class="fa fa-edit"></i> Editar parámetros
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="table-responsive caja_altura_fija_con_scroll">
          <table class="table table-hover table-bordered table-data-calculos">
            <thead>
              <tr>
                <th>CODIGO TITULO</th>
                <th>NOMBRE</th>
                <th>VALOR NOMINAL</th>
                <th>VALOR DE RESCATE</th>
                <th>FRECUENCIA DE PAGO</th>
              </tr>
            </thead>
            <tbody>
              <% @rm_inversiones.each do |inversion| %>
              <tr>
                <td><%= inversion.codigo %></td>
                <td><%= inversion.nombre %></td>
                <td class="texto_derecha"><%= inversion.valor_nominal %></td>
                <td class="texto_derecha"><%= inversion.valor_rescate %></td>
                <td class="texto_centrado"><%= Rm::RmDuration::FRECUENCIAS.map{|x| x.first if x.include?(inversion.frecuencia_pago)}.compact.first %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
	</div>
</div>